server:
  port: 9090
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rmdt-demo-member
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  dubbo:
    application: rmdt-demo-member-server
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    provider:
      timeout: 50000
    consumer:
      check: false
      timeout: 50000
    base-package: org.rmdt.demo.service.impl
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.rmdt.demo.domain
logging:
    level:
        root: info
        cn.wolfcode.rmdt: debug
    path: ./log