server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
  dubbo:
    application: rmdt-demo-client
    registry:
      address: zookeeper://127.0.0.1:2181
    consumer:
      check: false
      timeout: 50000
logging:
    level:
        root: info
        cn.wolfcode.rmdt: debug
    path: ./log